### ISSUE TITLE
use submit request

### ISSUE THREAD

**Issue by keesfluitman** [vaparr/ha-overseerr#10]
Hello,

Im fairly new to Hassio.
Im just testing stuff, and wanted to try to get submit_movie_request into my dashboard as an input_text + button to activate an automation trigger/action.

I can't seem to find any properly working code / integration of such...but maybe Im just still too fresh and blind.

Could you help me? Or am I in the wrong place?

**Comment by vaparr** [comment]
Please re-open if you are still having issues.
