### ISSUE TITLE
HTTP Error 403. Check SSL configuration

### ISSUE THREAD

**Issue by nathagt** [vaparr/ha-overseerr#19]
I'm getting this error in the logs. I'm running 1.29.1 stable overseer. I've tried uninstalling and reinstalling. I have added the custom repository (and restarted HA) but feel like there should be a step to actually add the integration. It does not show up in the list of integrations after adding the repository. No sensors show up in developer tools. 

```
Logger: custom_components.overseerr
Source: custom_components/overseerr/__init__.py:115
Integration: overseerr ([documentation](https://github.com/vaparr/ha-overseerr), [issues](https://github.com/vaparr/ha-overseerr/issues))
First occurred: 10:10:57 AM (1 occurrences)
Last logged: 10:10:57 AM

Unable to setup Overseerr: HTTP Error 403. Check SSL configuration. {'status': 403, 'error': 'You do not have permission to access this endpoint'}

```
Home Assistant 2022.7.5
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.1 - latest

my configuration.yalml entry:

```
overseerr:
  host: 192.168.1.xx
  port: xx55
  api_key: my_api_key_here
  scan_interval: 600
```

**Comment by vaparr** [comment]
Looks like its not an SSL issue.  Error code 403 means bad authentication.  Check your OverSeerr API key is correct, and does not have any stray spaces

**Comment by nathagt** [comment]
You were right. It missed the =at the end of API on copy + paste. Thanks
