### ISSUE TITLE
last_request_username is equal to null in sensor.overseerr_pending_requests

### ISSUE THREAD

**Issue by hbooo** [vaparr/ha-overseerr#3]
**Describe the bug**
last_request_username is equal to null in sensor.overseerr_pending_requests

**What version of Overseerr are you running?**
Overseerr version : develop-b5fd1d520cd2a7be6e6356a25129e93af1caf542
ha-overseerr : 0.1.20

**To Reproduce**

1. Go to Overseer
2. Do a request
3. Check on HA for sensor.overseerr_pending_requests
4. Name is null (same with all sensor.overseerr_*)

**Expected behavior**
Name should be displayed, I guess this occurs since https://github.com/sct/overseerr/issues/264 because my users have no friendly names
![image](https://user-images.githubusercontent.com/242125/106284125-133c9380-6243-11eb-8ffb-ed777048a8ff.png)

**Screenshot**
![image](https://user-images.githubusercontent.com/242125/106286085-8d6e1780-6245-11eb-8c60-2927cf407d79.png)

**Comment by vaparr** [comment]
Should be fixed in 0.1.22

**Comment by hbooo** [comment]
It's ok now, thanks!
